travis:
  secure:
    BINSTAR_TOKEN: o8x4Qx7OYUvXIfwkfVZW2zCpzlze4GRNL/ESaYL/+KRirxfjcApsDfoxAlc37Am9Kss0J4n0c+31qHOTJY83g1+Pd0OW0vUQAOoSRM+Ky61lFp1edqpJkXz2H+/Q4I6xqarM+nEvdFAA0a2D5Mrf/3UchgyceixEPGcmnmDAFM1HLeTc8lT2aFvmSSRcmFrmHYpxN5OIjbq10BrkVgfb27IwLYtzB405chYooorJAtgRg5w9iwcjvhfZQ1p0X4tmOTl828QFkC88IMtO2ydoe5YheZFzo7yv0Jf2KXhihw90SGqSairre/K0GnGJMlWkBCPZ1XWXwY+uAa/pW2y2zBN5gR30oyP9/Ri77ukSAql8Hhnizp8Zcs7cY3Uf0eDZLxrfsYND+ytsKVQzHZctB4BrIVYXGKYaTWpxZ0m59MKaNr2R326KDwtehRkv5zfPAyTmEOVu5kQENT1oq+JHIlzN8R70jjnmAxRXaKbU7WAjZeRbMaBpu2CpF4XrInB9GIVrkGpQzIoQCCyQYjbn5N7kil7q5PZC+G+9xtbLoTvBrueuMMcAPoj+ApY7AtDvqI9kHOf6qvq8eMMstR4A1DM+sx5TgFMbCkM0OYG0+HF9VjeXFcbsLEB3W3C9IaPXr8zI6jqN6jVWgYsboSL3I+cTm6wE/rw4kZj805kid8g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
